// Turns the design and config source files into code the app imports.
// Runs before `dev` and `build`. Never edit the generated files by hand.
//
//   design/tokens.json            -> src/styles/tokens.generated.css   (Tailwind theme)
//   design/icons/*.svg            -> src/components/ui/icons.generated.ts
//   config/reserved-usernames.txt -> src/config/reserved-usernames.generated.ts

import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(join(root, p), "utf8");
const write = (p, text) => {
  mkdirSync(dirname(join(root, p)), { recursive: true });
  writeFileSync(join(root, p), text);
};
const HEADER = "Generated by scripts/generate.mjs. Do not edit.";

// ---------- tokens ----------
const tokens = JSON.parse(read("design/tokens.json"));

// Two greys the reference screens use that tokens.json doesn't name yet.
const extraColors = [
  { name: "ink-soft", value: "#3A3A40", usage: "Secondary UI text (labels, ghost buttons) in the screens." },
  { name: "line-strong", value: "#CFCFC8", usage: "Empty checkbox borders and dashed empty-state outlines." },
];

const css = [];
css.push(`/* ${HEADER} Source: design/tokens.json */`, "", "@theme {");
// Wipe Tailwind's default palette so off-brand colours (blue!) can't be used by accident.
css.push("  --color-*: initial;");
for (const c of [...tokens.color.tokens, ...extraColors]) css.push(`  --color-${c.name}: ${c.value};`);
css.push("  --color-white: #FFFFFF;", "");

css.push("  --radius-*: initial;");
for (const r of tokens.radius.tokens) css.push(`  --${r.name}: ${r.value};`);
css.push("");

for (const s of tokens.spacing.tokens) css.push(`  --${s.name}: ${s.value};`);
css.push("");

for (const group of tokens.type.groups) {
  for (const s of group.styles) {
    css.push(`  --text-${s.name}: ${s.fontSize};`);
    css.push(`  --text-${s.name}--line-height: ${s.lineHeight};`);
    if (s.letterSpacing) css.push(`  --text-${s.name}--letter-spacing: ${s.letterSpacing};`);
    css.push(`  --text-${s.name}--font-weight: ${s.fontWeight};`);
  }
}
css.push("}", "");

// The logo stroke geometry, mirrored for Arabic.
const hl = Object.fromEntries(tokens.highlight.tokens.map((t) => [t.name, t.value]));
css.push(":root {");
for (const [k, v] of Object.entries(hl)) css.push(`  --${k}: ${v};`);
css.push("}");
css.push('[dir="rtl"] {');
css.push(`  --hl-skew: ${hl["hl-skew"].replace(/^-/, "")};`);
css.push(`  --hl-rotate: ${hl["hl-rotate"].replace(/^-/, "")};`);
css.push("}", "");
write("src/styles/tokens.generated.css", css.join("\n"));

// ---------- icons ----------
const iconDir = join(root, "design/icons");
const icons = {};
for (const file of readdirSync(iconDir).filter((f) => f.endsWith(".svg")).sort()) {
  const svg = readFileSync(join(iconDir, file), "utf8");
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "").trim();
  icons[file.replace(/\.svg$/, "")] = inner;
}
write(
  "src/components/ui/icons.generated.ts",
  `// ${HEADER} Source: design/icons/*.svg\n\n` +
    `export const iconBodies = ${JSON.stringify(icons, null, 2)} as const;\n\n` +
    `export type IconName = keyof typeof iconBodies;\n`,
);

// ---------- reserved usernames ----------
const reserved = read("config/reserved-usernames.txt")
  .split(/\r?\n/)
  .map((l) => l.trim().toLowerCase())
  .filter((l) => l && !l.startsWith("#"));
write(
  "src/config/reserved-usernames.generated.ts",
  `// ${HEADER} Source: config/reserved-usernames.txt\n\n` +
    `export const reservedUsernames: ReadonlySet<string> = new Set(${JSON.stringify([...new Set(reserved)])});\n`,
);

console.log(`generate: ${Object.keys(icons).length} icons, ${reserved.length} reserved names, tokens ok`);
